#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# if you use npx to install dependencies， use next line 
# npx --no -- lint-staged

# if you use yarn to install dependencies， use next line
yarn lint-staged
